In [8]:
import torch
import fasttext
import torch.nn
import pandas as pd
import numpy as np

In [3]:
torch.rand(50, 10)

tensor([[2.1969e-01, 2.0204e-01, 7.4227e-02, 4.8288e-01, 2.5578e-01, 9.8200e-01,
         8.1767e-01, 2.4750e-01, 3.2467e-02, 4.4457e-01],
        [8.2134e-01, 5.6919e-01, 1.6790e-01, 2.2054e-01, 8.3967e-01, 8.2551e-01,
         5.3072e-01, 9.4100e-01, 4.6185e-01, 3.1954e-01],
        [4.1773e-01, 7.4487e-01, 1.6388e-01, 2.4693e-01, 3.3744e-01, 3.7711e-01,
         2.4320e-01, 7.4618e-01, 1.0891e-01, 8.1969e-02],
        [8.6818e-01, 2.8101e-01, 1.5458e-01, 7.6317e-02, 2.3300e-01, 9.5962e-01,
         5.7520e-01, 2.9543e-01, 3.4179e-01, 3.5040e-01],
        [2.9278e-01, 4.2774e-01, 1.5241e-01, 6.2160e-01, 6.5064e-01, 9.2628e-02,
         7.3330e-01, 6.3998e-01, 1.7768e-01, 3.4348e-01],
        [3.6094e-01, 7.0825e-01, 8.8259e-01, 2.6447e-01, 5.5409e-01, 1.5825e-01,
         5.0743e-01, 5.8728e-02, 4.1888e-01, 6.7353e-01],
        [9.2190e-01, 6.7815e-01, 2.3121e-01, 9.2773e-01, 7.1300e-01, 8.7143e-01,
         1.0195e-03, 8.1593e-02, 6.5719e-01, 4.1592e-01],
        [9.0431e-01, 2.1170

In [5]:
titles = pd.read_csv(f"data/titles.csv")
titles_dict = dict(zip(titles.asin, titles.title))
graph_dict = np.load(f"data/graph_dict.npy", allow_pickle=True)

In [17]:
graph_dict

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [7]:
edge_index = torch.tensor([graph_dict.item().get("dst"),graph_dict.item().get("src")])
set_edge_index = set(torch.cat([edge_index[0],edge_index[1]]).numpy().tolist())
vocab = dict(zip(graph_dict.item().get("vocab_v"), graph_dict.item().get("vocab_k")))
title_df = []
for i in set_edge_index:
    title_df.append(vocab[i])

In [9]:
title_df

'B011TPNIOO'

In [10]:
titles = pd.DataFrame(title_df, columns=["asin"]).merge(titles,on="asin").fillna("error")
new_vocab = dict(zip(set_edge_index, np.arange(len(set_edge_index))))

In [12]:
new_vocab

{786435: 0,
 524291: 1,
 262151: 2,
 524296: 3,
 786441: 4,
 262155: 5,
 262158: 6,
 786447: 7,
 786446: 8,
 524311: 9,
 25: 10,
 26: 11,
 786459: 12,
 30: 13,
 47: 14,
 524339: 15,
 786488: 16,
 786489: 17,
 524345: 18,
 524346: 19,
 61: 20,
 69: 21,
 70: 22,
 524363: 23,
 83: 24,
 786519: 25,
 786520: 26,
 524384: 27,
 524385: 28,
 786530: 29,
 98: 30,
 786532: 31,
 786534: 32,
 103: 33,
 110: 34,
 786543: 35,
 113: 36,
 114: 37,
 115: 38,
 117: 39,
 786549: 40,
 119: 41,
 104230: 42,
 524411: 43,
 262274: 44,
 786571: 45,
 524427: 46,
 786572: 47,
 524430: 48,
 524433: 49,
 146: 50,
 153: 51,
 364753: 52,
 786590: 53,
 786591: 54,
 524449: 55,
 524454: 56,
 786600: 57,
 786601: 58,
 786602: 59,
 786603: 60,
 170: 61,
 786605: 62,
 524461: 63,
 184: 64,
 185: 65,
 786618: 66,
 524475: 67,
 786622: 68,
 786623: 69,
 262338: 70,
 479338: 71,
 524484: 72,
 524485: 73,
 197: 74,
 524487: 75,
 524488: 76,
 524486: 77,
 202: 78,
 524491: 79,
 524492: 80,
 786629: 81,
 786635: 82,
 207: 83,

In [14]:
ft = fasttext.util.download_model('en', if_exists='ignore')  # English
#ft = fasttext.load_model(f'data/fasttext')

AttributeError: module 'fasttext' has no attribute 'util'

In [ ]:

x = [ft.get_sentence_vector(i) for i in titles.title.values]
# x = torch.rand((len(set_),50))


edge_index = torch.tensor([[new_vocab[i] for i in graph_dict.item().get("dst")],
                           [new_vocab[i] for i in graph_dict.item().get("src")]])
#data = Data(torch.tensor(x), edge_index)

In [3]:
import torch_geometric # torch_sparse, torch_scatter needed

In [6]:
ju = torch_geometric.nn.GATConv(3,3)

In [15]:
x = torch.rand(1, 10)
torch.exp(x)

tensor([[2.6349, 2.1630, 1.6182, 1.6838, 1.3377, 1.4920, 1.6256, 1.6339, 1.7371,
         2.2183]])

In [80]:
def _GAT(emb: torch.tensor, edge: torch.tensor) -> torch.tensor:
    # should add test on matrix positive semi-definite
    emb_dim = emb.size(dim=0)
    edge_dim = edge.size(dim=1)
    e = torch.exp(torch.matmul(emb, torch.t(emb)))
    att_mask = torch.zeros(emb_dim, emb_dim, dtype=torch.int)
    edge = edge - 1
    for i in range(edge_dim):
        att_mask[edge[0, i], edge[1, i]] = 1
        att_mask[edge[1, i], edge[0, i]] = 1
    e_adj = e * att_mask
    den = e_adj.sum(dim=1)
    output = e.t()/den
    return output.t()

In [81]:
x = torch.rand(5, 50)
edge_idx = torch.tensor([[1, 1, 1, 1, 3, 4, 2, 2, 5, 5], [3, 4, 5, 2, 2, 5, 4, 5, 3, 1]])
_GAT(x, edge_idx)

tensor([[5.7690e+01, 1.0288e-02, 2.2624e-02, 8.3535e-01, 1.3173e-01],
        [4.1806e-01, 7.3311e+00, 3.8382e-02, 3.5379e-01, 1.8977e-01],
        [8.7385e-01, 3.6485e-02, 2.7855e+00, 4.5022e-01, 8.9665e-02],
        [7.4864e-01, 7.8030e-03, 1.0446e-02, 5.3645e+01, 2.4356e-01],
        [3.2091e-01, 1.1377e-02, 5.6552e-03, 6.6205e-01, 1.8216e+00]])

In [77]:
torch.rand(5, 50)

tensor([[0.8766, 0.4007, 0.1633, 0.7260, 0.1738, 0.0155, 0.9866, 0.3804, 0.2972,
         0.4922, 0.0159, 0.5795, 0.8394, 0.6456, 0.9783, 0.1004, 0.2158, 0.2108,
         0.1336, 0.0184, 0.2577, 0.2061, 0.1826, 0.9161, 0.5521, 0.3995, 0.8508,
         0.8500, 0.8470, 0.1157, 0.9594, 0.7116, 0.8570, 0.5860, 0.9802, 0.3832,
         0.8145, 0.0058, 0.7193, 0.8290, 0.8195, 0.1707, 0.7694, 0.4258, 0.8122,
         0.0460, 0.7492, 0.5962, 0.4674, 0.1421],
        [0.3145, 0.6398, 0.6307, 0.1848, 0.0457, 0.5892, 0.1195, 0.3138, 0.4133,
         0.7032, 0.0825, 0.2719, 0.5281, 0.0975, 0.2124, 0.5148, 0.6765, 0.7853,
         0.0640, 0.6103, 0.7625, 0.4467, 0.0145, 0.2253, 0.7009, 0.3940, 0.5153,
         0.8286, 0.3955, 0.0527, 0.0014, 0.2011, 0.5724, 0.0694, 0.1095, 0.0196,
         0.1608, 0.7893, 0.8916, 0.3762, 0.7408, 0.0720, 0.9956, 0.7485, 0.2643,
         0.9527, 0.2857, 0.5238, 0.3789, 0.3951],
        [0.5331, 0.0227, 0.6842, 0.5282, 0.4295, 0.7264, 0.6918, 0.6725, 0.6564,
         

In [68]:
x = torch.rand(5)
print(x)
x.t()

tensor([0.0792, 0.6708, 0.1733, 0.4421, 0.4331])


tensor([0.0792, 0.6708, 0.1733, 0.4421, 0.4331])

In [60]:
11.121/44.1331

0.25198773709528677